### ISSUE TITLE
Will this work with windows?

### ISSUE THREAD

**Issue by zachdyer** [dstrunk/atom-dark-vim#1]
I put `atom_dark.vim` into my colors folder and did `colorscheme atom_dark` but it didn't work. The colors don't look right.

**Comment by dstrunk** [comment]
Sorry, but I have no idea. This is an old repository that needs to be pruned (see numerous references to http://github.com/tomasr/molokai theme). Best laid plans and all that.

I'll close this issue and delete the repository in the next 48 hours.
